### ISSUE TITLE
suggestions for README

### ISSUE THREAD

**Issue by dtmak1** [tlee8/cheesePoofs#3]
I recommend that you make the statement of the problem just the objective. This might just be a personal preference, but I think it provides a little more clarity. 

The recursive abstraction looks great. I think adjacent is nice, but potentially confusing. (Is it just NESW or is it all surrounding 8 positions?)

I think the base case could use a little refining. 
1) Recording the path seems like a version n thing, so perhaps focus on answering the statement of the problem when the explorer's on the treasure.
2) I agree that the wall is a base case, but I think dealing with it differently might make your life easier. If you print 'no solution', you might get a lot of lines bc the backtracking works til it hits the base case (i.e. every step you try to take that doesn't work will return no solution). One thought is to just 'return' which will allow the for loop to continue. 

I hadn't thought of using something like isLegal! I haven't spent too much time thinking on it, but it seems brilliant and much faster than what I was thinking, so thank you!

**Comment by tlee8** [comment]
Thanks Dylan for your helpful comments, and we realized the huge problem returning no solution once we were in a wall would cause. This probably saved us a lot of headache in the future.
